<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Mage_Postepay
 * @copyright  Copyright (c) 2009 TeleType - Oto tortorella
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none">
        <li>
            <div class="input-box">
                <?php if ($this->getMethod()->getPayWithinXDays() > 0): ?>
                    <?php echo $this->__('Please transfer the money within %s days to the following Postepay card', $this->getMethod()->getPayWithinXDays()); ?>:
                <?php else: ?>
                    <?php echo $this->__('Please transfer the money to the following Postepay card'); ?>:
                <?php endif; ?><br /><br />
                <table>
                    <tbody>
                    <?php if ($this->getMethod()->getCardHolder()): ?>
                        <?php echo '<tr><td><label>' . $this->__('Card holder') . '</label>:</td><td>' . $this->getMethod()->getCardHolder() . '</td></tr>'; ?>
                    <?php endif; ?>
                    <?php if ($this->getMethod()->getCardNumber()): ?>
                        <?php echo '<tr><td><label>' . $this->__('Card number') . '</label>:</td><td>' . $this->getMethod()->getCardNumber() . '</td></tr>'; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
			  <?php if ($this->getMethod()->getCustomText()): ?>
                    <br />
                    <?php echo $this->getMethod()->getCustomText(); ?><br />
                <?php endif; ?>
            </div>
        </li>
    </ul>
</fieldset>
