<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Mage_BollettinoPostale
 * @copyright  Copyright (c) 2008 TeleType - Oto Tortorella
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<p>
    <?php echo $this->getMethod()->getTitle(); ?><br />
    <div style="font-style: italic;"><?php echo $this->__('Account info'); ?></div>
    <table>
        <tbody>
        <?php if ($this->getMethod()->getAccountHolder()): ?>
            <?php echo '<tr><td><label>' . $this->__('Account holder') . '</label>:</td><td>' . $this->getMethod()->getAccountHolder() . '</td></tr>'; ?>
        <?php endif; ?>
        <?php if ($this->getMethod()->getAccountNumber()): ?>
            <?php echo '<tr><td><label>' . $this->__('Account number') . '</label>:</td><td>' . $this->getMethod()->getAccountNumber() . '</td></tr>'; ?>
        <?php endif; ?>
        </tbody>
    </table>
    <?php if ($this->getMethod()->getCustomText()): ?>
        <br />
        <?php echo $this->getMethod()->getCustomText(); ?><br />
    <?php endif; ?>
</p>
