<?php if (count($this->sellingFormatTemplates) > 1 || count($this->descriptionsTemplates) > 1 || count($this->listingsTemplates) > 1 || count($this->synchronizationsTemplates) > 1 || !$this->sellingFormatTemplatesDropDown || !$this->descriptionsTemplatesDropDown || !$this->listingsTemplatesDropDown || !$this->synchronizationsTemplatesDropDown): ?>
    
    <p class="switcher">

        <?php if (count($this->sellingFormatTemplates) > 1 || !$this->sellingFormatTemplatesDropDown): ?>
            <label for="selling_format_template_switcher"><?php echo $this->__('Selling Format Template'); ?>:</label>
            <?php if ($this->sellingFormatTemplatesDropDown): ?>
                <select id="selling_format_template_switcher" name="selling_format_template_switcher" style="min-width: 100px; width: 130px; margin-right: 30px;" onchange="return switchTemplate(this,'<?php echo $this->sellingFormatTemplateUrl; ?>','filter_selling_format_template');">
                    <option value="0" <?php if ($this->selectedSellingFormatTemplate == 0) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('All Templates') ?></option>
                    <?php foreach ($this->sellingFormatTemplates as $id => $title): ?>
                        <option value="<?php echo $id; ?>" <?php if ($this->selectedSellingFormatTemplate == $id) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($title); ?></option>
                    <?php endforeach; ?>
                </select>
            <?php else: ?>
                <input type="text" id="selling_format_template_autocomplete" selected_id="" style="width: 130px; margin-right: 30px;">
            <?php endif; ?>
        <?php endif; ?>

        <?php if (count($this->descriptionsTemplates) > 1 || !$this->descriptionsTemplatesDropDown): ?>
            <label for="description_template_switcher"><?php echo $this->__('Description Template'); ?>:</label>
            <?php if ($this->descriptionsTemplatesDropDown): ?>
                <select id="description_template_switcher" name="description_template_switcher" style="min-width: 100px; width: 130px; margin-right: 30px;" onchange="return switchTemplate(this,'<?php echo $this->descriptionTemplateUrl; ?>','filter_description_template');">
                    <option value="0" <?php if ($this->selectedDescriptionTemplate == 0) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('All Templates') ?></option>
                    <?php foreach ($this->descriptionsTemplates as $id => $title): ?>
                        <option value="<?php echo $id; ?>" <?php if ($this->selectedDescriptionTemplate == $id) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($title); ?></option>
                    <?php endforeach; ?>
                </select>
            <?php else: ?>
                <input type="text" id="description_template_autocomplete" selected_id="" style="width: 130px; margin-right: 30px;">
            <?php endif; ?>
        <?php endif; ?>

        <?php if (count($this->listingsTemplates) > 1 || !$this->listingsTemplatesDropDown): ?>
            <label for="listing_template_switcher"><?php echo $this->__('General Template'); ?>:</label>
            <?php if ($this->listingsTemplatesDropDown): ?>
                <select id="listing_template_switcher" name="listing_template_switcher" style="min-width: 100px; width: 130px; margin-right: 30px;" onchange="return switchTemplate(this,'<?php echo $this->listingTemplateUrl; ?>','filter_listing_template');">
                    <option value="0" <?php if ($this->selectedListingTemplate == 0) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('All Templates') ?></option>
                    <?php foreach ($this->listingsTemplates as $id => $title): ?>
                        <option value="<?php echo $id; ?>" <?php if ($this->selectedListingTemplate == $id) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($title); ?></option>
                    <?php endforeach; ?>
                </select>
            <?php else: ?>
                <input type="text" id="listing_template_autocomplete" selected_id="" style="width: 130px; margin-right: 30px;">
            <?php endif; ?>
        <?php endif; ?>

        <?php if (count($this->synchronizationsTemplates) > 1 || !$this->synchronizationsTemplatesDropDown): ?>
            <label for="synchronization_template_switcher"><?php echo $this->__('Synchronization Template') ?>:</label>
            <?php if ($this->synchronizationsTemplatesDropDown): ?>
                <select id="synchronization_template_switcher" name="synchronization_template_switcher" style="min-width: 100px; width: 130px;" onchange="return switchTemplate(this,'<?php echo $this->synchronizationTemplateUrl; ?>','filter_synchronization_template');">
                    <option value="0" <?php if ($this->selectedSynchronizationTemplate == 0) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->__('All Templates') ?></option>
                    <?php foreach ($this->synchronizationsTemplates as $id => $title): ?>
                        <option value="<?php echo $id; ?>" <?php if ($this->selectedSynchronizationTemplate == $id) echo 'selected="selected"'; ?>><?php echo Mage::helper('M2ePro')->escapeHtml($title); ?></option>
                    <?php endforeach; ?>
                </select>
            <?php else: ?>
                <input type="text" id="synchronization_template_autocomplete" selected_id="" style="width: 130px;">
            <?php endif; ?>
        <?php endif; ?>

    </p>

    <script type="text/javascript">

        function switchTemplate(obj,url,urlParamName)
        {
            if (obj.value == 0) {
                setLocation(url);
            } else {
                setLocation(url+urlParamName+'/'+obj.value+'/');
            }
        }
        
        autoCompleteHandler = new AutoComplete();
        
        <?php if (!$this->sellingFormatTemplatesDropDown): ?>
            autoCompleteHandler.bind('selling_format_template_autocomplete',
                                      "<?php echo $this->getUrl('*/adminhtml_general/searchAutocomplete', array('model' => Mage::getResourceModel('M2ePro/SellingFormatTemplates')->getMainTable())) ?>",
                                      "<?php echo $this->selectedSellingFormatTemplate; ?>",
                                      "<?php echo $this->selectedSellingFormatTemplateValue; ?>",
                                      function (id) 
                                      {
                                          obj = {value: id};
                                          switchTemplate(obj, '<?php echo $this->sellingFormatTemplateUrl; ?>', 'filter_selling_format_template');
                                      }
                                      );
        <?php endif; ?> 
            
        <?php if (!$this->descriptionsTemplatesDropDown): ?>
            autoCompleteHandler.bind('description_template_autocomplete',
                                      "<?php echo $this->getUrl('*/adminhtml_general/searchAutocomplete', array('model' => Mage::getResourceModel('M2ePro/DescriptionsTemplates')->getMainTable())) ?>",
                                      "<?php echo $this->selectedDescriptionTemplate; ?>",
                                      "<?php echo $this->selectedDescriptionTemplateValue; ?>",
                                      function (id) 
                                      {
                                          obj = {value: id};
                                          switchTemplate(obj, '<?php echo $this->descriptionTemplateUrl; ?>', 'filter_description_template');
                                      }
                                      );
        <?php endif; ?>
        
        <?php if (!$this->listingsTemplatesDropDown): ?>
            autoCompleteHandler.bind('listing_template_autocomplete',
                                      '<?php echo $this->getUrl('*/adminhtml_general/searchAutocomplete', array('model' => Mage::getResourceModel('M2ePro/ListingsTemplates')->getMainTable())) ?>',
                                      "<?php echo $this->selectedListingTemplate; ?>",
                                      "<?php echo $this->selectedListingTemplateValue; ?>",
                                      function (id) 
                                      {
                                          obj = {value: id};
                                          switchTemplate(obj, '<?php echo $this->listingTemplateUrl; ?>', 'filter_listing_template');
                                      }
                                      );
        <?php endif; ?>
        
        <?php if (!$this->synchronizationsTemplatesDropDown): ?>
            autoCompleteHandler.bind('synchronization_template_autocomplete',
                                      '<?php echo $this->getUrl('*/adminhtml_general/searchAutocomplete', array('model' => Mage::getResourceModel('M2ePro/SynchronizationsTemplates')->getMainTable())) ?>',
                                      "<?php echo $this->selectedSynchronizationTemplate; ?>",
                                      "<?php echo $this->selectedSynchronizationTemplateValue; ?>",
                                      function (id) 
                                      {
                                          obj = {value: id};
                                          switchTemplate(obj, '<?php echo $this->synchronizationTemplateUrl; ?>', 'filter_synchronization_template');
                                      }
                                      );
        <?php endif; ?>

    </script>

<?php endif; ?>