<?php $_order = $this->getOrder() ?>
<div id="store_information">
<?php echo Mage::getStoreConfig('general/store_information/name');?><br/>
<?php echo str_replace("\n","<br/>",Mage::getStoreConfig('general/store_information/address'));?><br/>
<?php if($store_phone = Mage::getStoreConfig('general/store_information/phone')):?>
T: <?php echo $store_phone?>
<?php endif;?>
</div>
<h1 class="a-center"><?php echo $this->__("Invoice");?></h1>
<?php echo $this->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?php echo $_order->getId() ?>"/>
<?php echo $this->getItemsHtml() ?>
<div class="clear"></div>
<div class="entry-edit">
    <?php echo $this->getChildHtml('order_totals') ?>
</div>
<div class="clear"></div>
<script type="text/javascript">
//<![CDATA[
document.observe("dom:loaded",function(){
    window.print();
    window.onfocus = function() { window.close(); }
    //setTimeout('document.location.href = "<?php echo $this->getUrl("*/*/index");?>";',5000);    
});
//]]>
</script>
<?php echo $this->getChildHtml('popup_window');?>
<script type="text/javascript">
//<![CDATA[
    /**
     * Retrieve gift options tooltip content
     */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
            if (element.down(0)) {
                headerLine = element.down(0).innerHTML;
                contentLine = element.down(0).next().innerHTML;
                if (contentLine.length > 30) {
                    contentLine = contentLine.slice(0,30) + '...';
                }
                contentLines.push(headerLine + ' ' + contentLine);
            }
        });
        return contentLines.join('<br/>');
    }
    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
//]]>
</script>

