<div class="box-left">
    <div class="entry-edit" id="magento_block_orders_general" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
                <?php echo Mage::helper('M2ePro')->__('eBay Order');?> # <?php echo $this->order->getData('ebay_order_id'); ?>
                <?php if ((int)$this->order->getData('selling_manager_record_number') > 0) { ?>
                    [ <?php echo Mage::helper('M2ePro')->__('Selling Manager') . ': # ' . $this->order->getData('selling_manager_record_number') ?> ]
                <?php } ?>
            </h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table cellspacing="0" class="form-list">
                    <tbody>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Magento Order #');?></td>
                            <td class="value">
                                <strong>
                                    <?php if (!is_null($this->real_magento_order_id)) { ?>

                                        <?php if (!is_null($this->real_magento_order_id)) { ?>
                                            <a href="<?php echo $this->getUrl('adminhtml/sales_order/view/', array('order_id' => $this->order->getData('magento_order_id'))); ?>" target="_blank"><?php echo $this->real_magento_order_id; ?></a>
                                        <?php } else { ?>
                                            <?php echo $this->order->getData('magento_order_id'); ?>
                                        <?php } ?>

                                    <?php } else { ?>

                                        <?php echo Mage::helper('M2ePro')->__('N/A'); ?>

                                    <?php } ?>
                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Sale Time');?></td>
                            <td class="value"><strong><?php echo Mage::helper('core')->formatDate($this->order->getData('created_date'), 'medium', true); ?></strong></td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Update Time');?></td>
                            <td class="value"><strong><?php echo Mage::helper('core')->formatDate($this->order->getData('update_time'), 'medium', true); ?></strong></td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Order Status'); ?></td>
                            <td class="value">
                                <strong>

                                    <b><?php echo Mage::helper('M2ePro')->__('Checkout'); ?>: </b>

                                    <?php if ($this->order->isCheckoutCompleted()) { ?>
                                        <span style="color: green;"><?php echo Mage::helper('M2ePro')->__('Completed'); ?></span>
                                    <?php } else {
                                        echo Mage::helper('M2ePro')->__('Incomplete');
                                    } ?>

                                    <br />

                                    <b><?php echo Mage::helper('M2ePro')->__('Payment'); ?>: </b>

                                    <?php if ($this->order->isPaymentCompleted()) { ?>
                                        <span style="color: green;"><?php echo Mage::helper('M2ePro')->__('Paid'); ?></span>

                                    <?php } else if ($this->order->isPaymentFailed()) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('Unknown Error'); ?>

                                    <?php } else { ?>
                                        <!-- TODO: receive and show error from eBay -->
                                        <?php echo Mage::helper('M2ePro')->__('Waiting'); ?>
                                    <?php } ?>

                                    <br />

                                    <b><?php echo Mage::helper('M2ePro')->__('Shipping'); ?>: </b>

                                    <?php if ($this->order->isShippingCompleted()) { ?>
                                        <span style="color: green;"><?php echo Mage::helper('M2ePro')->__('Shipped'); ?></span>

                                    <?php } else if ($this->order->isShippingInProcess()) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('Not Shipped'); ?>

                                    <?php } else if ($this->order->isShippingMethodNotSelected()) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('Waiting'); ?>

                                    <?php } else { ?>
                                        <?php echo Mage::helper('M2ePro')->__('Unknown Error'); ?>
                                    <?php } ?>

                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Account');?></td>
                            <td class="value">
                                <strong>

                                    <?php if (!$this->order->getAccount()->getId()) { ?>
                                        <span style="color: red;"><?php echo Mage::helper('M2ePro')->__('Deleted'); ?></span>

                                    <?php } else { ?>

                                        <?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getAccount()->getTitle()); ?>

                                        <?php echo '(' . ($this->order->getAccount()->isModeProduction() ? Mage::helper('M2ePro')->__('Production') : Mage::helper('M2ePro')->__('Sandbox')) . ')'; ?>

                                    <?php }?>

                                </strong>
                            </td>
                        </tr>

                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>


<div class="box-right">
    <div class="entry-edit" id="magento_block_orders_buyer" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Buyer Information');?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table cellspacing="0" class="form-list">
                    <tbody>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Customer Name');?></td>
                            <td class="value">
                                <strong>

                                    <?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('buyer_name')) ?><br/>

                                    <?php if ($this->order->getData('buyer_email') != 'Invalid Request') { ?>
                                        &lt;<?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('buyer_email')); ?>&gt;<br />
                                    <?php } ?>

                                    <?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('buyer_userid')) ?>

                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Shipping Address');?></td>
                            <td class="value">
                                <strong>

                                    <?php if (is_array($this->shipping_address)) { ?>

                                        <?php if (isset($this->shipping_address['company']) && $this->shipping_address['company'] != '') { ?>
                                            <?php echo Mage::helper('M2ePro')->escapeHtml($this->shipping_address['company']); ?><br />
                                        <?php } ?>

                                        <?php if (isset($this->shipping_address['street']) && isset($this->shipping_address['street'][0]) && $this->shipping_address['street'][0] != '') { ?>
                                            <?php echo Mage::helper('M2ePro')->escapeHtml($this->shipping_address['street'][0]); ?><br />
                                        <?php } ?>

                                        <?php if (isset($this->shipping_address['city']) && $this->shipping_address['city'] != '') { ?>
                                            <?php echo Mage::helper('M2ePro')->escapeHtml($this->shipping_address['city']); ?>
                                        <?php } ?>

                                        <?php if (isset($this->shipping_address['region']) && $this->shipping_address['region'] != '') { ?>
                                            <?php echo ', ' . Mage::helper('M2ePro')->escapeHtml($this->shipping_address['region']); ?>
                                        <?php } ?>

                                        <?php if (isset($this->shipping_address['postcode']) && $this->shipping_address['postcode'] != '') { ?>
                                            <?php echo ', ' . Mage::helper('M2ePro')->escapeHtml($this->shipping_address['postcode']); ?><br />
                                        <?php } ?>

                                        <?php if (isset($this->shipping_address['country_id']) && $this->shipping_address['country_id'] != '') { ?>
                                            <?php echo Mage::helper('M2ePro')->escapeHtml($this->shipping_address['country_id']); ?><br />
                                        <?php } ?>

                                        <?php if (isset($this->shipping_address['telephone']) && $this->shipping_address['telephone'] != '') { ?>
                                            <?php echo 'T: ' . Mage::helper('M2ePro')->escapeHtml($this->shipping_address['telephone']); ?><br />
                                        <?php } ?>

                                        <?php if (isset($this->shipping_address['fax']) && $this->shipping_address['fax'] != '') { ?>
                                            <?php echo 'F: ' . Mage::helper('M2ePro')->escapeHtml($this->shipping_address['fax']); ?>
                                        <?php } ?>

                                    <?php } ?>

                                </strong>
                            </td>
                        </tr>

                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>

<br clear="all" />

<?php if ($this->order->hasTax()) { ?>
    <div class="box-left">
        <div class="entry-edit" id="magento_block_orders_tax" collapseable="no">

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('eBay Tax Information');?></h4>
                <div class="form-buttons"></div>
            </div>

            <div class="fieldset">
                <div class="hor-scroll">

                    <table cellspacing="0" class="form-list">
                        <tbody>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Tax Percent');?></td>
                            <td class="value">
                                <strong><?php echo $this->order->getData('sales_tax_percent')."%"; ?></strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Tax State');?></td>
                            <td class="value">
                                <strong><?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('sales_tax_state')); ?></strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Shipping Included In Tax');?></td>
                            <td class="value">
                                <strong><?php echo ($this->order->getData('sales_tax_shipping_included') == 1) ? Mage::helper('M2ePro')->__('Yes') : Mage::helper('M2ePro')->__('No');?></strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Tax Amount');?></td>
                            <td class="value">
                                <strong><?php echo Mage::helper('M2ePro')->convertCurrencyNameToCode($this->order->getData('currency'), $this->order->getData('sales_tax_amount')); ?></strong>
                            </td>
                        </tr>

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
<?php } ?>
        

<br clear="all" />


<div class="box-left">
    <div class="entry-edit" id="magento_block_orders_payment" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Payment Information');?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Order Currency');?></td>
                            <td class="value"><strong><?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('currency')); ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Payment Date');?></td>
                            <td class="value"><strong><?php echo $this->order->getData('payment_time') ? Mage::helper('core')->formatDate($this->order->getData('payment_time'), 'medium', true) : Mage::helper('M2ePro')->__('N/A'); ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Payment Method');?></td>
                            <td class="value"><strong><?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('payment_used')); ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('eBay Account'); ?></td>
                            <td class="value"><strong><?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('buyer_userid')); ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('eBay Final Fee');?></td>
                            <td class="value">
                                <strong>
                                    <?php if ($this->order->getData('final_value_fee') <= 0) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('N/A'); ?>
                                    <?php } else { ?>
                                        <?php echo Mage::helper('M2ePro')->convertCurrencyNameToCode($this->order->getCurrency(), round($this->order->getData('final_value_fee'), 2)); ?>
                                    <?php } ?>
                                </strong>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <?php if ($this->order->hasExternalTransactions()) { ?>
                    <br />
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td colspan="2" class="label" style="width: 100%">
                                    <h4><?php echo Mage::helper('M2ePro')->__('External Transactions'); ?></h4>
                                    <?php echo $this->getChildHtml('order_external_transactions'); ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                <?php } ?>

            </div>
        </div>

    </div>
</div>


<div class="box-right">
    <div class="entry-edit" id="magento_block_orders_shipping" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Shipping & Handling Information');?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">

                <table class="form-list" cellspacing="0">
                    <tbody>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Shipping Selected Service');?></td>
                            <td class="value">
                                <strong>
                                    <?php if (is_null($this->order->getData('shipping_selected_service'))) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('N/A'); ?>
                                    <?php } else { ?>
                                        <?php echo Mage::helper('M2ePro')->escapeHtml($this->order->getData('shipping_selected_service')); ?>
                                    <?php } ?>
                                </strong>
                            </td>
                        </tr>

                        <tr>
                            <td class="label"><?php echo Mage::helper('M2ePro')->__('Shipping Cost');?></td>
                            <td class="value">
                                <strong>
                                    <?php if (!$this->order->getData('shipping_selected_cost')) { ?>
                                        <?php echo Mage::helper('M2ePro')->__('N/A'); ?>
                                    <?php } else { ?>
                                        <?php echo Mage::helper('M2ePro')->convertCurrencyNameToCode($this->order->getCurrency(), $this->order->getData('shipping_selected_cost')); ?>
                                    <?php } ?>
                                </strong>
                            </td>
                        </tr>

                        <?php if ($shippingTime = $this->order->getData('shipping_time')) { ?>
                            <tr>
                                <td class="label"><?php echo Mage::helper('M2ePro')->__('Shipping Time');?></td>
                                <td class="value"><strong><?php echo Mage::helper('core')->formatDate($shippingTime, 'medium', true); ?></strong></td>
                            </tr>
                        <?php } ?>

                        <?php if (count($this->order->getShippingTrackingDetails(true))) { ?>

                            <tr>
                                <td class="grid" colspan="2">
                                    <br/>
                                    <h4><?php echo Mage::helper('M2ePro')->__('Tracking Details'); ?></h4>
                                    <table class="data" cellpadding="0" cellspacing="0">
                                        <thead>
                                            <tr class="headings">
                                                <th><?php echo Mage::helper('M2ePro')->__('Carrier'); ?></th>
                                                <th><?php echo Mage::helper('M2ePro')->__('Number'); ?></th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            <?php foreach ($this->order->getShippingTrackingDetails(true) as $key => $trackingDetail) { ?>
                                                <tr class="<?php echo $key%2?'odd':'even'?>">
                                                    <td><?php echo $trackingDetail['title']; ?></td>
                                                    <td><?php echo $trackingDetail['number']; ?></td>
                                                </tr>
                                            <?php } ?>

                                        </tbody>
                                    </table>
                                </td>
                            </tr>

                        <?php } ?>

                    </tbody>
                </table>

            </div>
        </div>

    </div>

    <div class="entry-edit" id="magento_block_orders_message" collapseable="no">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Checkout Message From Buyer');?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset">
            <?php if ($checkoutMessage = $this->order->getCheckoutMessage()) { ?>
                <?php echo strip_tags($checkoutMessage, '<b><strong><br>'); ?>
            <?php } else { ?>
                <?php echo Mage::helper('M2ePro')->__('None') ?>
            <?php } ?>
        </div>

    </div>
</div>


<br clear="all" />

<div class="entry-edit" id="magento_block_orders_transaction" collapseable="no">
    <div class="entry-edit-head">
        <h4 class="icon-head head-products"><?php echo Mage::helper('M2ePro')->__('Transaction Item'); ?></h4>
    </div>
</div>

<div class="grid np">
    <div class="hor-scroll">
         <?php echo $this->getChildHtml('order_items'); ?>
    </div>
</div>

<br clear="all" />

<div class="box-left">

    <div class="entry-edit" id="magento_block_orders_history" collapseable="no">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('M2ePro')->__('Log History');?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset">
            <?php echo $this->getChildHtml('order_logs'); ?>
        </div>

    </div>

</div>


<div class="box-right entry-edit" collapseable="no">

    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('M2ePro')->__('Order Totals');?></h4>
    </div>

    <div class="order-totals">
        <table cellspacing="0" width="100%">
            <tbody>

                <tr>
                    <td class="label"><?php echo Mage::helper('M2ePro')->__('Subtotal').$this->getTaxSuffix(); ?></td>
                    <td><span class="price"><?php echo Mage::helper('M2ePro')->convertCurrencyNameToCode($this->order->getCurrency(), $this->order->getSubtotalPrice());?></span></td>
                </tr>

                <tr>
                    <td class="label"><?php echo Mage::helper('M2ePro')->__('Shipping & Handling').$this->getTaxSuffix(); ?></td>
                    <td><span class="price"><?php echo Mage::helper('M2ePro')->convertCurrencyNameToCode($this->order->getCurrency(), $this->order->getShippingPrice());?></span></td>
                </tr>

            </tbody>

            <tfoot>

                <tr>
                    <td class="label">
                        <strong><big><?php echo Mage::helper('M2ePro')->__('Grand Total');?></big></strong>
                    </td>
                    <td class="emph"><big><strong><span class="price"><?php echo Mage::helper('M2ePro')->convertCurrencyNameToCode($this->order->getCurrency(), $this->order->getGrandTotalPrice());?></span></strong></big></td>
                </tr>

                <tr>
                    <td class="label"><small><?php echo Mage::helper('M2ePro')->__('Amount Paid'); ?></small></td>
                    <td><span class="price"><small><?php echo Mage::helper('M2ePro')->convertCurrencyNameToCode($this->order->getCurrency(), $this->order->getAmountPaid());?></small></span></td>
                </tr>

                <tr>
                    <td class="label"><small><?php echo Mage::helper('M2ePro')->__('Amount Saved'); ?></small></td>
                    <td><span class="price"><small><?php echo Mage::helper('M2ePro')->convertCurrencyNameToCode($this->order->getCurrency(), $this->order->getAmountSaved());?></small></span></td>
                </tr>

            </tfoot>
        </table>

    </div>
</div>


