<table>
    <tr>
        <?php if ($this->getInfo()->getAdditionalData()) { ?>
            <?php if ($this->getEbayPaymentMethod()) { ?>
                <td style="width: 200px;"><?php echo Mage::helper('M2ePro')->__('Payment Method'); ?></td>
                <td><strong><?php echo $this->escapeHtml($this->getEbayPaymentMethod()); ?></strong></td>
            <?php } ?>
        <?php } ?>
    </tr>
    <?php if ($this->getInfo()->getAdditionalData()) { ?>
        <?php if ($this->getEbayOrderId()) { ?>
            <tr>
                <td style="width: 200px;"><?php echo Mage::helper('M2ePro')->__('eBay Order ID') ?></td>
                <td><strong><?php echo $this->escapeHtml($this->getEbayOrderId()); ?></strong></td>
            </tr>
        <?php } ?>
        <?php if ($this->getEbayFinalValueFee()) { ?>
            <tr>
                <td style="width: 200px;"><?php echo Mage::helper('M2ePro')->__('eBay Final Fee') ?></td>
                <td><strong><?php echo $this->escapeHtml($this->getEbayFinalValueFee()); ?></strong></td>
            </tr>
        <?php } ?>
        <?php if (count($this->getExternalTransactions())) { ?>
            <tr>
                <td class="grid" colspan="2">
                    <br/>
                    <h4><?php echo Mage::helper('M2ePro')->__('External Transactions'); ?></h4>
                    <table class="data" cellpadding="0" cellspacing="0">
                        <thead>
                            <tr class="headings">
                                <th><?php echo Mage::helper('M2ePro')->__('Transaction #'); ?></th>
                                <th><?php echo Mage::helper('M2ePro')->__('Fee'); ?></th>
                                <th><?php echo Mage::helper('M2ePro')->__('Amount'); ?></th>
                                <th><?php echo Mage::helper('M2ePro')->__('Date'); ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                                $externalTransactions = $this->getExternalTransactions();
                                $order = $this->getOrder();
                            ?>
                            <?php foreach ($externalTransactions as $key => $externalTransaction) { ?>
                                <tr class="<?php echo $key%2?'odd':'even'?>">
                                    <td>
                                        <?php if (strtolower($this->getEbayPaymentMethod()) == 'paypal') { ?>
                                            <a href="<?php echo $this->getUrl('M2ePro/adminhtml_orders/goToPaypalTransactionPage', array('transaction_id' => $externalTransaction['ebay_id'])); ?>" target="_blank"><?php echo $externalTransaction['ebay_id']; ?></a>
                                        <?php } else { ?>
                                            <?php echo $externalTransaction['ebay_id']; ?>
                                        <?php } ?>
                                    </td>
                                    <td><?php echo !is_null($order) ? $order->formatPrice($externalTransaction['fee']) : $externalTransaction['fee']; ?></td>
                                    <td><?php echo !is_null($order) ? $order->formatPrice($externalTransaction['sum']) : $externalTransaction['sum']; ?></td>
                                    <td><?php echo Mage::helper('core')->formatDate($externalTransaction['time'], 'medium', true); ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </td>
            </tr>
        <?php } ?>
    <?php } ?>
</table>